name: test-kustomize-build-action

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ensure all kustomizations are buildable
        uses: yanniszark/github-actions/kustomize-build-github-action@master
